image: dlang2/ldc-ubuntu

build:linux:
  stage: build
  script: ci/build-release.sh
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  cache:
    paths:
      - .dub/
  artifacts:
    paths:
      - ddmg
    expire_in: 1 week
      
unittests:
  stage: test
  script: ci/unittests.sh
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
        
blargg-cpu_instrs:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/blargg/cpu_instrs/cpu_instrs.gb" --testMode "blargg_serial" --testMaxInstrs 25000000

blargg-instr_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/blargg/instr_timing/instr_timing.gb" --testMode "blargg_serial" --testMaxInstrs 300000

blargg-mem_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/blargg/mem_timing/mem_timing.gb" --testMode "blargg_serial" --testMaxInstrs 700000

blargg-mem_timing-2:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/blargg/mem_timing-2/mem_timing.gb" --testMode "blargg_memory" --testMaxInstrs 1200000

blargg-oam_bug:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/blargg/oam_bug/oam_bug.gb" --testMode "blargg_memory" --testMaxInstrs 6000000
  allow_failure: true  # OAM bug not yet implemented

blargg-dmg_sound:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/blargg/dmg_sound/dmg_sound.gb" --testMode "blargg_memory" --testMaxInstrs 3400000
  allow_failure: true  # Sound not yet implemented

# No CGB support, so the cgb_sound test never finishes.
# TODO figure out how to automate the blargg halt_bug test rom

mooneye-rapid_di_ei:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/rapid_di_ei.gb" --testMode "mooneye"

mooneye-oam_dma_start:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/oam_dma_start.gb" --testMode "mooneye"

mooneye-boot_regs-dmgABC:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/boot_regs-dmgABC.gb" --testMode "mooneye"
# XXX: Varies depending on hardware: For DMG ABC only. DDMG targets just the DMG ABC for now.

mooneye-reti_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/reti_timing.gb" --testMode "mooneye"

mooneye-call_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/call_timing.gb" --testMode "mooneye"

mooneye-reti_intr_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/reti_intr_timing.gb" --testMode "mooneye"

#mooneye-boot_regs-mgb:
#  stage: test
#  dependencies:
#    - build:linux
#  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/boot_regs-mgb.gb" --testMode "mooneye"
# XXX: Varies depending on hardware: For MGB only

mooneye-ei_sequence:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ei_sequence.gb" --testMode "mooneye"

mooneye-jp_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/jp_timing.gb" --testMode "mooneye"

mooneye-ei_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ei_timing.gb" --testMode "mooneye"

mooneye-oam_dma_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/oam_dma_timing.gb" --testMode "mooneye"

mooneye-call_cc_timing2:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/call_cc_timing2.gb" --testMode "mooneye"

mooneye-halt_ime1_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/halt_ime1_timing.gb" --testMode "mooneye"

mooneye-halt_ime1_timing2-GS:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/halt_ime1_timing2-GS.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-tima_reload:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/timer/tima_reload.gb" --testMode "mooneye"

mooneye-tma_write_reloading:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/timer/tma_write_reloading.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-tim10:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/timer/tim10.gb" --testMode "mooneye"

mooneye-tim00:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/timer/tim00.gb" --testMode "mooneye"

mooneye-tim11:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/timer/tim11.gb" --testMode "mooneye"

mooneye-tim01:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/timer/tim01.gb" --testMode "mooneye"

mooneye-tima_write_reloading:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/timer/tima_write_reloading.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-tim11_div_trigger:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/timer/tim11_div_trigger.gb" --testMode "mooneye"

mooneye-div_write:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/timer/div_write.gb" --testMode "mooneye"

mooneye-tim10_div_trigger:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/timer/tim10_div_trigger.gb" --testMode "mooneye"

mooneye-tim00_div_trigger:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/timer/tim00_div_trigger.gb" --testMode "mooneye"

mooneye-rapid_toggle:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/timer/rapid_toggle.gb" --testMode "mooneye"

mooneye-tim01_div_trigger:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/timer/tim01_div_trigger.gb" --testMode "mooneye"

#mooneye-boot_regs-sgb:
#  stage: test
#  dependencies:
#    - build:linux
#  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/boot_regs-sgb.gb" --testMode "mooneye"
# XXX: Varies depending on hardware: For SGB only

mooneye-jp_cc_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/jp_cc_timing.gb" --testMode "mooneye"

mooneye-call_timing2:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/call_timing2.gb" --testMode "mooneye"

mooneye-ld_hl_sp_e_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ld_hl_sp_e_timing.gb" --testMode "mooneye"

mooneye-push_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/push_timing.gb" --testMode "mooneye"

#mooneye-boot_hwio-dmg0:
#  stage: test
#  dependencies:
#    - build:linux
#  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/boot_hwio-dmg0.gb" --testMode "mooneye"
# XXX: Varies depending on hardware: For DMG 0 only

mooneye-rst_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/rst_timing.gb" --testMode "mooneye"

#mooneye-boot_hwio-S:
#  stage: test
#  dependencies:
#    - build:linux
#  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/boot_hwio-S.gb" --testMode "mooneye"
#  XXX: Varies depending on hardware: For SGB, SGB2

mooneye-mem_oam:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/bits/mem_oam.gb" --testMode "mooneye"

mooneye-reg_f:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/bits/reg_f.gb" --testMode "mooneye"

mooneye-unused_hwio-GS:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/bits/unused_hwio-GS.gb" --testMode "mooneye"

mooneye-div_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/div_timing.gb" --testMode "mooneye"

mooneye-ret_cc_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ret_cc_timing.gb" --testMode "mooneye"

#mooneye-boot_regs-dmg0:
#  stage: test
#  dependencies:
#    - build:linux
#  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/boot_regs-dmg0.gb" --testMode "mooneye"
# XXX: Varies depending on hardware: For DMG 0 only

mooneye-ie_push:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/interrupts/ie_push.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-boot_hwio-dmgABCmgb:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/boot_hwio-dmgABCmgb.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.
# XXX: Varies depending on hardware: For DMG ABC and MGB only. DDMG targets just the DMG ABC for now.

mooneye-pop_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/pop_timing.gb" --testMode "mooneye"

mooneye-ret_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ret_timing.gb" --testMode "mooneye"

mooneye-oam_dma_restart:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/oam_dma_restart.gb" --testMode "mooneye"

mooneye-add_sp_e_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/add_sp_e_timing.gb" --testMode "mooneye"

mooneye-sources-dmgABCmgbS:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/oam_dma/sources-dmgABCmgbS.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.
# XXX: Varies depending on hardware: For DMG ABC, MGB, and SGB only. DDMG targets just the DMG ABC for now.

mooneye-basic:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/oam_dma/basic.gb" --testMode "mooneye"

mooneye-reg_read:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/oam_dma/reg_read.gb" --testMode "mooneye"

mooneye-halt_ime0_nointr_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/halt_ime0_nointr_timing.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-vblank_stat_intr-GS:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ppu/vblank_stat_intr-GS.gb" --testMode "mooneye"
# XXX: Varies depending on hardware: For DMG, MGB, SGB, SGB2. DDMG targets just the DMG for now.

mooneye-intr_2_mode0_timing_sprites:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ppu/intr_2_mode0_timing_sprites.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-stat_irq_blocking:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ppu/stat_irq_blocking.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-intr_1_2_timing-GS:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ppu/intr_1_2_timing-GS.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.
# XXX: Varies depending on hardware: For DMG, MGB, SGB, SGB2. DDMG targets just the DMG for now.

mooneye-lcdon_timing-dmgABCmgbS:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ppu/lcdon_timing-dmgABCmgbS.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.
# XXX: Varies depending on hardware: For DMG ABC, MGB, SGB, SGB2. DDMG targets just the DMG ABC for now.

mooneye-intr_2_mode0_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ppu/intr_2_mode0_timing.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-lcdon_write_timing-GS:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ppu/lcdon_write_timing-GS.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.
# XXX: Varies depending on hardware: For DMG, MGB, SGB, SGB2. DDMG targets just the DMG for now.

mooneye-hblank_ly_scx_timing-GS:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ppu/hblank_ly_scx_timing-GS.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.
# XXX: Varies depending on hardware: For DMG, MGB, SGB, SGB2. DDMG targets just the DMG for now.

mooneye-intr_2_0_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ppu/intr_2_0_timing.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-stat_lyc_onoff:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ppu/stat_lyc_onoff.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-intr_2_mode3_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ppu/intr_2_mode3_timing.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-intr_2_oam_ok_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/ppu/intr_2_oam_ok_timing.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-call_cc_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/call_cc_timing.gb" --testMode "mooneye"

mooneye-halt_ime0_ei:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/halt_ime0_ei.gb" --testMode "mooneye"

mooneye-intr_timing:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/intr_timing.gb" --testMode "mooneye"

mooneye-if_ie_registers:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/if_ie_registers.gb" --testMode "mooneye"

mooneye-di_timing-GS:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/di_timing-GS.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.
# XXX: Varies depending on hardware: For DMG, MGB, SGB, SGB2. DDMG targets just the DMG for now.

mooneye-boot_sclk_align-dmgABCmgb:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/serial/boot_sclk_align-dmgABCmgb.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.
# XXX: Varies depending on hardware: For DMG ABC only. DDMG targets just the DMG ABC for now.

#mooneye-boot_regs-sgb2:
#  stage: test
#  dependencies:
#    - build:linux
#  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/acceptance/boot_regs-sgb2.gb" --testMode "mooneye"
# XXX: Varies depending on hardware: For SGB 2 only

mooneye-rom_1Mb:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/emulator-only/mbc1/rom_1Mb.gb" --testMode "mooneye"

mooneye-rom_512Kb:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/emulator-only/mbc1/rom_512Kb.gb" --testMode "mooneye"

mooneye-bits_ram_en:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/emulator-only/mbc1/bits_ram_en.gb" --testMode "mooneye"

mooneye-ram_64Kb:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/emulator-only/mbc1/ram_64Kb.gb" --testMode "mooneye"

mooneye-rom_2Mb:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/emulator-only/mbc1/rom_2Mb.gb" --testMode "mooneye"

mooneye-ram_256Kb:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/emulator-only/mbc1/ram_256Kb.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-rom_4Mb:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/emulator-only/mbc1/rom_4Mb.gb" --testMode "mooneye"

mooneye-multicart_rom_8Mb:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/emulator-only/mbc1/multicart_rom_8Mb.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-rom_8Mb:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/emulator-only/mbc1/rom_8Mb.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

mooneye-rom_16Mb:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/mooneye-gb_hwtests/emulator-only/mbc1/rom_16Mb.gb" --testMode "mooneye"
  allow_failure: true  # HW characteristic not yet implemented. TODO pass this test.

