image: dlang2/ldc-ubuntu

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-release:
       stage: build
       script: ci/build-release.sh
       artifacts:
               paths:
               - ddmg

unittests:
        script: ci/unittests.sh
