image: dlang2/ldc-ubuntu

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
build:linux:
  stage: build
  script: ci/build-release.sh
  artifacts:
    paths:
      - ddmg
    expire_in: 1 week
        
unittests:
  stage: test
  script: ci/unittests.sh
          
blargg-cpu_instrs:
  stage: test
  dependencies:
    - build:linux
  script: ./ddmg --rom "./test-roms/blargg/cpu_instrs/cpu_instrs.gb" --testMode "blargg" --testMaxInstrs 25000000
              